### ISSUE TITLE
Restrict the token to only currently logged in user in the example Cloud function

### ISSUE THREAD

**Issue by matijse** [layerhq/layer-parse-module#3]
In the current example code for the Parse Cloud function, a userID for any user can be supplied. Since Parse automatically has the user that is currently logged in available under `request.user`, why not use that?

For example: 

```
Parse.Cloud.define("generateToken", function(request, response) {
    var currentUser = request.user;
    if (!currentUser) throw new Error('You need to be logged in!');
    var userID = currentUser.id;
    var nonce = request.params.nonce;
    if (!nonce) throw new Error('Missing nonce parameter');
        response.success(layer.layerIdentityToken(userID, nonce));
});
```

**Comment by akshay9** [comment]
Infact this is the only way it should be done. else a person can manipulate the the userId in the android code and gain access to any account on layer. UserIds can be got from conversations/participants

**Comment by maju6406** [comment]
Sorry about the delay here, but I updated the main.js snippet to use the code you suggested.  Thanks!
